# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='lenght',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
