# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('specialty', models.CharField(max_length=255)),
                ('average_consult_duration', models.DurationField(default=datetime.timedelta(0, 1800))),
            ],
        ),
    ]
